-- Contact messages table (replaces Firebase contactus-messages collection)
CREATE TABLE IF NOT EXISTS public.contact_messages (
  id        bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  first_name  text NOT NULL,
  last_name   text NOT NULL,
  cellphone   text,
  email       text,
  title       text,
  message     text NOT NULL,
  created_at  timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE public.contact_messages ENABLE ROW LEVEL SECURITY;

-- Only authenticated users (admins) may read; inserts are open (contact form)
CREATE POLICY "contact_messages_insert" ON public.contact_messages
  FOR INSERT WITH CHECK (true);

CREATE POLICY "contact_messages_select_auth" ON public.contact_messages
  FOR SELECT USING (auth.role() = 'authenticated');

CREATE POLICY "contact_messages_delete_auth" ON public.contact_messages
  FOR DELETE USING (auth.role() = 'authenticated');

CREATE INDEX IF NOT EXISTS idx_contact_messages_created_at
  ON public.contact_messages (created_at DESC);
