-- Altar Responses Course table
CREATE TABLE IF NOT EXISTS public.altar_responses_course (
  id        bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  full_name text NOT NULL,
  phone_number text NOT NULL,
  dob       date NOT NULL,
  church    text NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE public.altar_responses_course ENABLE ROW LEVEL SECURITY;

-- Allow anyone to insert (public form submission)
CREATE POLICY "altar_responses_insert" ON public.altar_responses_course
  FOR INSERT WITH CHECK (true);

-- Only authenticated users (admins) may read and delete
CREATE POLICY "altar_responses_select_auth" ON public.altar_responses_course
  FOR SELECT USING (auth.role() = 'authenticated');

CREATE POLICY "altar_responses_delete_auth" ON public.altar_responses_course
  FOR DELETE USING (auth.role() = 'authenticated');

CREATE INDEX IF NOT EXISTS idx_altar_responses_created_at
  ON public.altar_responses_course (created_at DESC);
